"""initial_schema

Revision ID: 6999658ea4b8
Revises: 
Create Date: 2026-04-09 21:15:13.248662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6999658ea4b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('patronymic', sa.String(length=255), nullable=True),
    sa.Column('group', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('student_id'),
    schema='public'
    )
    op.create_table('recording',
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('path_screen', sa.String(length=255), nullable=False),
    sa.Column('path_webcam', sa.String(length=255), nullable=False),
    sa.Column('path_processed_webcam', sa.String(length=255), nullable=True),
    sa.Column('path_processed_screen', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'DONE', name='recordingstatus'), nullable=False),
    sa.Column('processed_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('suspicion_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['public.student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recording_id'),
    schema='public'
    )
    op.create_table('notification',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('sent_date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('DONE', name='notificationtype'), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['public.recording.recording_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id'),
    schema='public'
    )
    op.create_table('suspicious_interval',
    sa.Column('sus_id', sa.UUID(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['public.recording.recording_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sus_id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suspicious_interval', schema='public')
    op.drop_table('notification', schema='public')
    op.drop_table('recording', schema='public')
    op.drop_table('student', schema='public')
    # ### end Alembic commands ###
