"""create_database

Revision ID: b85fb8d56670
Revises: 
Create Date: 2026-04-05 22:25:08.783656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b85fb8d56670'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notification_recording_id_fkey'), 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'recording', ['recording_id'], ['recording_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('recording_student_id_fkey'), 'recording', type_='foreignkey')
    op.create_foreign_key(None, 'recording', 'student', ['student_id'], ['student_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('suspicious_interval_recording_id_fkey'), 'suspicious_interval', type_='foreignkey')
    op.create_foreign_key(None, 'suspicious_interval', 'recording', ['recording_id'], ['recording_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suspicious_interval', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('suspicious_interval_recording_id_fkey'), 'suspicious_interval', 'recording', ['recording_id'], ['recording_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'recording', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('recording_student_id_fkey'), 'recording', 'student', ['student_id'], ['student_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'notification', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('notification_recording_id_fkey'), 'notification', 'recording', ['recording_id'], ['recording_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
